1.impot necessary libraies

In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

2. import dataset

In [2]:
claimants_data = pd.read_csv("claimants.csv.csv")
claimants_data

      CASENUM  ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0           5         0     0.0       1.0       0.0    50.0  34.940
1           3         1     1.0       0.0       0.0    18.0   0.891
2          66         1     0.0       1.0       0.0     5.0   0.330
3          70         0     0.0       1.0       1.0    31.0   0.037
4          96         1     0.0       1.0       0.0    30.0   0.038
...       ...       ...     ...       ...       ...     ...     ...
1335    34100         1     0.0       1.0       0.0     NaN   0.576
1336    34110         0     1.0       1.0       0.0    46.0   3.705
1337    34113         1     1.0       1.0       0.0    39.0   0.099
1338    34145         0     1.0       0.0       0.0     8.0   3.177
1339    34153         1     1.0       1.0       0.0    30.0   0.688

[1340 rows x 7 columns]

3.Data Understanding

In [3]:
claimants_data.shape

(1340, 7)

In [4]:
claimants_data.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

In [5]:
claimants_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   CASENUM   1340 non-null   int64
 1   ATTORNEY  1340 non-null   int64
 2   CLMSEX    1328 non-null   float64
 3   CLMINSUR  1299 non-null   float64
 4   SEATBELT  1292 non-null   float64
 5   CLMAGE    1151 non-null   float64
 6   LOSS      1340 non-null   float64
dtypes: float64(5), int64(2)
memory usage: 73.4 KB

In [6]:
claimants_data.isna().sum()

CASENUM       0
ATTORNEY      0
CLMSEX       12
CLMINSUR     41
SEATBELT     48
CLMAGE      189
LOSS          0
dtype: int64

4.Data Prepartion

In [7]:
# 4.1 data cleaning

claimants_data.dropna(inplace=True)


# 4.2 Seperate your inputs and outputs

x = claimants_data.drop(['CASENUM','ATTORNEY'],axis=1)

y = claimants_data ["ATTORNEY"]

In [8]:
x

      CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0        0.0       1.0       0.0    50.0  34.940
1        1.0       0.0       0.0    18.0   0.891
2        0.0       1.0       0.0     5.0   0.330
3        0.0       1.0       1.0    31.0   0.037
4        0.0       1.0       0.0    30.0   0.038
...      ...       ...       ...     ...     ...
1334     1.0       1.0       0.0    16.0   0.060
1336     1.0       1.0       0.0    46.0   3.705
1337     1.0       1.0       0.0    39.0   0.099
1338     1.0       0.0       0.0     8.0   3.177
1339     1.0       1.0       0.0    30.0   0.688

[1096 rows x 5 columns]

In [9]:
y

0       0
1       1
2       1
3       0
4       1
       ..
1334    1
1336    0
1337    1
1338    0
1339    1
Name: ATTORNEY, Length: 1096, dtype: int64

5. Model Buliding

In [10]:
logistic_model= LogisticRegression()


x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.20,random_state=32)

6. Model Traning & Testing

In [11]:
logistic_model.fit(x_train,y_train)

y_pred_train = logistic_model.predict(x_train)
y_pred_test = logistic_model.predict(x_test)

8.Model Evaluation

In [12]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

print(accuracy_score(y_test,y_pred_test))

0.6318181818181818

In [13]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.65      0.53      0.58       107
           1       0.62      0.73      0.67       113

    accuracy                           0.63       220
   macro avg       0.63      0.63      0.63       220
weighted avg       0.63      0.63      0.63       220

In [14]:

print(confusion_matrix(y_test,y_pred_test))

[[57 50]
 [31 82]]

## 9.Model Deployment ##

In [15]:
from pickle import dump

In [16]:
dump(obj= logistic_model, file= open(file= "logistic_intelligence_file.pkl", mode= 'wb'))

In [17]:
from pickle import load

In [20]:
logistic_intel_pkl = load(file=open(file = "logistic_intelligence_file.pkl",mode='rb'))
logistic_intel_pkl

LogisticRegression()

In [22]:
logistic_intel_pkl.predict(x)

array([0, 0, 1, ..., 1, 0, 1], dtype=int64)